# Generated by Django 5.1.4 on 2025-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customeraddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
