# Generated by Django 5.1.4 on 2025-01-13 06:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customeraddress_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
    ]
