# Generated by Django 5.1.4 on 2025-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="address_type",
            field=models.CharField(
                choices=[("H", "Home"), ("B", "Work"), ("O", "Other")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
