# Generated by Django 5.1.4 on 2025-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_order_options_order_coupon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
