# Generated by Django 5.1.4 on 2025-01-18 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
