# Generated by Django 5.1.4 on 2025-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_remove_order_coupon_remove_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
