# Generated by Django 5.1.4 on 2025-01-20 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_razorpay_order_id_order_razorpay_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_id",
        ),
    ]
