# Generated by Django 5.1.4 on 2025-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_remove_order_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponusage",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
