# Generated by Django 5.1.4 on 2025-01-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_couponusage_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponusage",
            name="title",
        ),
        migrations.AddField(
            model_name="coupon",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
