# Generated by Django 5.1.4 on 2025-01-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_alter_couponusage_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SHIPPED", "SHIPPED"),
                    ("PROCESSING", "PROCESSING"),
                    ("DELIVERED", "DELIVERED"),
                    ("CANCELLED", "CANCELLED"),
                    ("COMPLETED", "COMPLETED"),
                    ("PAYMENT_FAILED", "PAYMENT_FAILED"),
                ],
                max_length=20,
            ),
        ),
    ]
