# Generated by Django 5.1.4 on 2025-01-13 06:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_carouselitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="image_link",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_link",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="product_category_image",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="product_image"
            ),
            preserve_default=False,
        ),
    ]
