# Generated by Django 5.1.4 on 2025-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                related_name="products", to="products.productimage"
            ),
        ),
    ]
