# Generated by Django 5.1.4 on 2025-01-13 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
    ]
