# Generated by Django 5.1.4 on 2025-01-13 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_productimage_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
