# Generated by Django 5.1.4 on 2025-01-13 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="slug",
        ),
    ]
