# Generated by Django 5.1.4 on 2025-01-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_favouriteproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
