# Generated by Django 5.1.4 on 2025-01-16 14:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselitem",
            name="imagelink",
        ),
        migrations.AddField(
            model_name="carouselitem",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="carausel_image"
            ),
            preserve_default=False,
        ),
    ]
