# Generated by Django 5.1.4 on 2025-01-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_remove_carouselitem_imagelink_carouselitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
