# Generated by Django 5.1.4 on 2025-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
