# Generated by Django 5.1.4 on 2025-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
