# Generated by Django 5.1.4 on 2025-01-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
